Repository araclx/humantic, pull requests merged in 2020-08, with the labels that each got.

#26 feat: migration to microservice architecture
  .circleci/config.yml
  .gitignore
  package.json
  services/api/cluster.json
  services/api/package.json
  services/api/src/bin/worker.ts
  services/api/src/controllers/project.controller.ts
  services/api/src/interfaces/user.interface.ts
  services/api/src/middlewares/jwt.middleware.ts
  services/api/src/middlewares/logger.middleware.ts
  services/api/src/middlewares/rbac.middleware.ts
  services/api/src/modules/mongoose.module.ts
  services/api/src/modules/sentry.module.ts
  services/api/src/routers/project.router.ts
  services/api/src/services/gateway/gateway.service.ts
  services/api/src/services/project/project.controller.ts
  services/api/src/services/project/project.requester.ts
  services/api/src/services/project/project.router.ts
  services/api/src/services/project/project.service.ts
  services/api/tests/app.ts
  services/api/webpack.config.js
  services/api/yarn.lock
  services/ui/src/organisms/App/App.css
  services/ui/src/organisms/app/App.js
  yarn.lock
Labels: enhancement

#34 docs: add codacy badge
  README.md
Labels: size/XS

#35 ci: add dockerhub automation
  .circleci/config.yml
Labels: size/M
